### ISSUE TITLE
[Feature Request] New HeliPort Icon

### ISSUE THREAD

**Issue by chris1111** [OpenIntelWireless/HeliPort#148]
This is the New HeliPort Icon I suggest 😄 For my part, I think the blue WIFI icon looks too old-fashioned 🧐 ![67850724](https://user-images.githubusercontent.com/6248794/89318407-c047a200-d64c-11ea-838c-93313f6e5db8.png)

My Icon suggests shows the green bar of Wifi at the maximum of its connection.
![AppIcon](https://user-images.githubusercontent.com/6248794/89316000-84f7a400-d649-11ea-9ef8-c911220710e4.png)
Files .png and .icons attach
[AppIcon.png.zip](https://github.com/OpenIntelWireless/HeliPort/files/5023103/AppIcon.png.zip)
[AppIcon.icns.zip](https://github.com/OpenIntelWireless/HeliPort/files/5023106/AppIcon.icns.zip)

its look like this in Lunchpad 
![Capture d’écran, le 2020-08-04 à 11 59 43](https://user-images.githubusercontent.com/6248794/89316440-1ebf5100-d64a-11ea-9d05-4ef7405edf7f.png)

Hope you like it?
If not delete this post 
Thank you verry much for your work and effort!

**Comment by williambj1** [comment]
Thanks, we appreciate your time and effort but after some discussion, we decided not to accept your Icon.

- The AC on the icon is quite misleading since we not only support AC cards but also AX ones, and correctly itlwm doesn't make cards work in AC mode.
- We think our original icon matches Chrome and WhatsApp's flattened design and it doesn't look too bad.
- I personally think our icon should have vibrant colors instead of sticking with black and grey, Apple's icons are quite colorful as well.

Again, thanks for your interest and hard work.

**Comment by chris1111** [comment]
Thats not a big problem
![AppIcon](https://user-images.githubusercontent.com/6248794/89814240-d3f17d80-db10-11ea-8ad6-34ae729b4a4a.png)
