### ISSUE TITLE
[Bug] Network list not updated at startup casuing menu to shown empty networks list, no placeholder

### ISSUE THREAD

**Issue by igorkulman** [OpenIntelWireless/HeliPort#45]
**Describe the bug**
When you run the app the network scan is not done immediately so if you immediately open the menu you will get an empty list of networks and no placeholder saying "scanning" or something like that.

**To Reproduce**
1. Run the app
2. Immediately open the menu
3. Observe no networks in the list

**Expected behavior**
The app should start network scan immediately after startup, or at least show some placeholder

**Screenshots**
![Screenshot 2020-07-03 at 14 02 12](https://user-images.githubusercontent.com/4746070/86470289-6d23bc00-bd3b-11ea-9061-5792412c029b.png)

**Environment (please complete the following information):**
 - OS Version: 10.15.5
 - Software Version: `19c0386`

**Additional context**
Looking at code `updateNetworkList()` is called in `StatusMenu.init` but the network card state is not yet set to available (called with a delay) so scan is not done.

**Comment by ErrorErrorError** [comment]
Ideally it shouldn't even say "Wi-Fi: Connected" since now we can detect when the Wi-Fi is connected by the checkmark, however we can try to reduce the delay from which searching for networks gets called the first time the app is run.

**Comment by ErrorErrorError** [comment]
I think a way we could "fix" this issue is whenever the state is `ITL80211_S_RUN` to take the first item of the network list and set it to show visible with the correct information, i.e. SSID name, RSSI, Security, and updating the NetworkInfo from the extra options, since it has to wait until `updateNetworkList` is called. 

However, I am not sure if that would be the best way to fix this issue.

**Comment by zxystd** [comment]
try modify `get_network_list` function, delete `sleep(3);` and move `ioctl_set(IOCTL_80211_SCAN, &scan, sizeof(struct ioctl_scan))` below scan result.
